### ISSUE TITLE
Add handling for NHD reaches with AREASQKM==0 

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#145]
Two suggestions:
1. We currently compute an approximate area for these reaches using the length^2, but we could just keep using 0 area so that the data for these 0 area reaches are not counted toward to final area-weighted PRMS attribute value. However, some PRMS reaches will then not receive attributes because the whole area is 0, so some special handling could be needed for these reaches. (PRMS segs “287_1”, “614_1”, “878_1”,”903_1”). Also may not work for attributes that do not use an area-weighted value.
2. filter 0 area reaches out of `p1_nhdv2reaches_sf` and check how that impacts downstream targets. Some PRMS segments may not have any NHD reaches after this filter.

**Comment by jds485** [comment]
Decided as a group that we should update to use the network without divergences and 0 area NHD reaches (option 2) to get slightly more accurate attributes for PRMS reaches where there are reaches with 0 area NHD segments. In `drb-network-prep`, when a PRMS reach has only 1 NHD reach, that NHD reach is retained even if it has 0 for the catchment area. Our processing scrips already handle these reaches with a length^2 area approximation, so no additional edits should be needed. 

@lekoenig suggested checking how much different the PRMS attributes are before and after making this switch. I think we can do that by pulling the target version on S3 and making scatterplots or histograms of the differences.

**Comment by lekoenig** [comment]
In the crosswalk table built in drb-network-prep, we've added an argument to omit zero-area reaches from the list of returned COMIDs, motivated by this use case (https://github.com/USGS-R/drb-network-prep/issues/8). I didn't appreciate this at the time, but omitting the zero-area reaches makes the crosswalk table less useful/generalizable to other projects, because those reaches are needed for network navigation (e.g. building adjacency matrices for RGCN models, etc.). 

> filter 0 area reaches out of p1_nhdv2reaches_sf and check how that impacts downstream targets. Some PRMS segments may not have any NHD reaches after this filter.

I'm wondering about this and would appreciate input. If we keep the zero-area reaches in the crosswalk table, could we still handle those in the inland salinity pipeline as suggested above? For example, I could see a step where we modify `p2_drb_comids_all_tribs` or create a new target `p2_drb_comids_omit_zero_area_flines` that filters these reaches out and is then used as input to the downstream NHD attribute aggregation functions.

**Comment by jds485** [comment]
To create the crosswalk with 0 area segments in `drb-network-prep`, would that just require changing a TRUE to FALSE? It might be better to create 2 crosswalks (one with, one without), and then projects can choose which to select.

I'm thinking we would be duplicating effort in this repo by using a network with 0 area segments and then removing them, when the `drb-network-prep` functions already can do that (if I'm remembering correctly).

**Comment by lekoenig** [comment]
Yeah, the drb-network-prep functions currently do that, although I'm wondering about omitting that argument. We potentially run into a lot of permutations of the crosswalk table (with + without divergences x with + without zero-area flowlines). Omitting the zero-area flowlines within the inland salinity pipeline might allow for more streamlined code and outputs in drb-network-prep.

**Comment by jds485** [comment]
Okay, I didn't realize you were planning to delete that argument. I think it would be simpler to use the functions in `drb-network-prep`, but it would be possible to filter out the 0 area reaches in this repo. We would have to program in that at least 1 NHD catchment is retained for each PRMS reach, and maybe other checks from `drb-network-prep` to do this. If a lot would be copied, it seems better to make additional targets in `drb-network-prep` with the TRUE/FALSE combinations that each of the projects need. That way, another project could make use of the 0 area removed network (example, I think the PRMS-based stream temperature network could make use of this)

**Comment by lekoenig** [comment]
OK, thanks for this input. I'll consider this and get back to you.
