### ISSUE TITLE
Remove likely erroneous SC measurement

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#190]
Based on analysis by me and @lekoenig, we think that the daily recorded SC value for PRMS segment `111_1` on `1999-03-30` is likely in error. Cl and Na do not show high values and so it would be unlikely that SC could be ~30,000 uS/cm. 

This point contributes to about 10% of the model RMSE, so can have a large impact on results.

**Comment by lekoenig** [comment]
_Posting my comments here so that they are linked to this issue:_

re. our high value at 111_1 on 1999-03-30, my best guess is that that value is due to some sort of measurement/entry error, but there's no ancillary information that suggests the sample is questionable.

First, that segment-date only has one sample and it's coming from a discrete sample at USGS site 01421618. I didn't see anything unusual in the harmonized dataset, but I pulled the raw data myself from WQP just to make sure. Chloride and Sodium were also recorded at the same time but don't show similar spikes like I would expect with a conductance value in excess of 30,000 uS/cm. All metadata from WQP suggests it was a routine sample under stable hydrologic conditions. 

![high_salinity_data](https://user-images.githubusercontent.com/8785034/197856957-2ffbaa2b-0410-461e-83be-69d39330b608.png)

![high_salinity_graphic](https://user-images.githubusercontent.com/8785034/197857007-181929aa-68ca-4917-8eea-0c0a12e71ac4.png)

**Comment by lekoenig** [comment]
I also just noticed that this sample is a lab sample rather than a value from a field probe, so that's interesting. Anyway, the NY WSC is listed as the collecting organization, so I've emailed them to see if they have any additional information about this record. I'll let you know if I hear anything further.

**Comment by lekoenig** [comment]
My message was received, forwarded, and answered in less than 24 hr, hats off to the NY WSC! 🏆

Here's the response I got from Shawn Fisher, the Water Quality Specialist there:

> Unfortunately, this record is so old that we were not able to find field notes nor were the folks at the NWQL able to track down the exact source of the error. However, after chatting with colleagues at NWQL and our Troy lab, it appears that the single sample bottle (containing raw, unacidified water) that was sent to the lab for pH, SC, and ANC analyses was inadvertently acidified (likely in the field). Separate bottles are submitted for major ions and nutrients, hence the lack of corresponding ions to justify the elevated SC and low pH (which was measured at the lab to be 1.0). 
> 
>  I went into NWIS and rejected pcodes 00403 (pH) and 90095 (SC) and added a result-level comment to each as well as a sample-level comment noting the change so they will be visible to anyone who downloads the dataset in the future.

I don't know what the lag time is that this update would show up in the Water Quality Portal, but in the meantime this is ample reason to omit this particular record from our dataset.

**Comment by jds485** [comment]
Amazing! Thanks for reaching out. pH = 1.0 is scary acidic! I still prefer to remove this point in our most downstream target instead of updating the WQP data. I can code this removal so that it will still run if we update our WQP targets.
