### ISSUE TITLE
Check gauges for tidal influence to inform study reaches

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#30]
Tidal influence can extend up to 30 river km upstream of an estuary. We should check that our sites do not show this signal, or have a weak signal.

For reaches downstream of Trenton, NJ, check daily and instantaneous data within 30 km of the estuary for a tidal signal. I think that would appear in a simple Fourier frequency analysis.

**Comment by lekoenig** [comment]
I agree that some sort of spectral analysis would be a good way to check for tidal influence in the SC data. I started out by looking at a [site](https://waterdata.usgs.gov/nj/nwis/uv/?site_no=01412350&PARAmeter_cd=00010,00095,00300,00301,00400,63680) which we've previously omitted because we have strong reason to think it _is_ tidal - it's in Delaware Bay. I used this site as a control of sorts, to see what kind of signal we'd be looking for.

**Control site 01412350**

1. Download the data and pad the time steps
```
ts_data <- dataRetrieval::readNWISuv(
  siteNumbers = "01412350",parameterCd="00095",startDate = "1979-10-01",endDate = "2021-12-13",tz = "UTC") %>%
  dataRetrieval::renameNWISColumns() %>%
  rename("Value_Inst" = "Lower_SpecCond_Inst")

# Pad timestamps (we need continuous data for spectral analysis):
  ts_data_complete <- ts_data %>%
  tidyr::complete(dateTime = seq(lubridate::ymd_hms(min(dateTime)),lubridate::ymd_hms(max(dateTime)), by = '6 mins')) %>%
  # interpolate values for up to 10 timesteps (in this case, 1 hr):
  mutate(Value_Inst = zoo::na.approx(Value_Inst,maxgap=10))
```
2. For each time series, find the longest continuous stretch of non-NA values on which to perform spectral analysis
```
find_longest_cont_subset <- function(data){
  
  run <- rle(!is.na(data$Value_Inst))
  data$run <- rep(run$lengths,run$lengths)
  data$cond <- rep(run$values,run$lengths) 
  data_cont_subset <- data %>% 
    filter(cond==TRUE) %>%
    filter(run == max(run))
  
}

ts_data_subset <- find_longest_cont_subset(ts_data_complete)
```

3. Plot the power spectrum computed using discrete time fast fourier transform

```
plot_power_spectra <- function(data_subset,delta_t = 1/96,plot_title){
  
  # Calculate the frequency spectrum using fast fourier transform, fft:
  options(scipen=999)
  spect <- spectrum(data_subset$Value_Inst,plot=FALSE)
  
  # Convert frequency (cycles per sampling interval) to cycles per unit time by dividing by sampling interval:
  specx <- spect$freq/delta_t
  
  # Multiply spectrum by 2 to equal variance:
  specy <- 2*spect$spec
  
  # Plot power spectral density:
  plot(specx, specy, xlab="Frequency (cycles/day)", ylab="Spectral Density", type="l",log="xy",main=plot_title)
  
}

plot_power_spectra(ts_data_subset,delta_t=1/240,plot_title="USGS 01412350: Delaware Bay") 
```

![pwerspectrum_controlsite](https://user-images.githubusercontent.com/8785034/148114004-00ecd3aa-affd-4dc6-b93c-7b03e8798b88.png)

Here we see a clear spectal peak around 2/day, which is what we would expect for a tidal frequency. 

4. I don't have much experience with wavelet analysis, but I decided to give it a shot since environmental data may be inherently nonstationary. 

```
library(WaveletComp)
ts_data_subset$date <- ts_data_subset$dateTime
ts_wv <- analyze.wavelet(ts_data_subset, "Value_Inst",loess.span = 0,dt = 1/240)
# create wavelet plot
wt.image(ts_wv, n.levels = 250,legend.params = list(lab = "wavelet power levels"),siglvl = 0.05,
         col.contour="black",show.date=TRUE,periodlab = "Period (days)")
```

![wavelet_controlsite](https://user-images.githubusercontent.com/8785034/148114240-7d5d6b86-26ab-4019-9c43-0e890caf4437.png)

Wavelet transform similarly illustrates the ubiquity of the tidal frequency (with a period of ~0.5 days)

OK, cool! Now let's check out one of our inland sites.

First, identify sites we may want to investigate closer for tidal influence. As a conservative measure, I took the PRMS mainstem for the Delaware River south of Trenton, NJ and identified instantaneous sites within 30 km of that mainstem segment (n=42):

![sites_within_buff](https://user-images.githubusercontent.com/8785034/148114698-cced1c78-bddf-4728-aaaa-f262f1a44da8.png)



**Site 01483700**

![stjonesriver_psd](https://user-images.githubusercontent.com/8785034/148114862-4e60d540-9a4f-4678-9b50-e2293dd7171a.png)

We're not seeing any clear peaks in spectral power that would indicate tidal influence at this site. 

**I plan to apply this fourier transform analysis for the 42 sites that I've flagged as potentially influenced by tides/estuarine signals. Before I add those results here, does this approach seem reasonable?** Tagging @jds485, but any comments are welcome!

**Comment by jds485** [comment]
Thanks, looks great!

**Comment by lekoenig** [comment]
I calculated the power spectrum using fft for each of the 42 NWIS instantaneous sites described above as being close enough to the estuary to warrant further inspection. For simplicity - and because I was focused on signal at higher frequencies - I did not attempt to impute longer periods without data and instead ran fft on the longest continuous stretch of data. As a result (and because some sites only recently started reporting SC observations), these data chunks often span months, not years.

In summary, I did not find clear evidence of tidal influence for the majority of these sites:

- For 33/42 of the sites I did not see any spectral peaks that would suggest a tidal signal
- Based on the power spectral density plots I followed-up with wavelet analysis for 9/42 of the sites
- **There are 2 sites where some tidal influence seems likely**: 1) site [014670261](https://waterdata.usgs.gov/pa/nwis/uv/?site_no=014670261&PARAmeter_cd=00400,00095,00010,00300) along the Delaware River mainstem, and 2) site [01477120](https://waterdata.usgs.gov/nj/nwis/uv?site_no=01477120), Raccoon Creek near Swedesboro, NJ. The power spectral density and wavelet plots for these sites are included below.

![psd_site_014670261](https://user-images.githubusercontent.com/8785034/148234602-6e897261-108f-43c9-a759-9d6b916a59dc.png)
![wavelet_014670261](https://user-images.githubusercontent.com/8785034/148234611-d540cf3c-cc39-4b4d-9e96-f10a8702649e.png)
![psd_site_01477120](https://user-images.githubusercontent.com/8785034/148234649-7b331b63-c9fd-422a-9880-b51b7590182e.png)
![wavelet_01477120](https://user-images.githubusercontent.com/8785034/148234659-4b45b00a-9e1f-4468-8a1d-1a3b4b32e8e6.png)

The locations of these two sites are shown in red:

![flagged_sites](https://user-images.githubusercontent.com/8785034/148235853-47d389d3-a3a7-4d76-8eeb-55d12683ea59.png)


Clearly these frequencies are not as strong as in the "control" site above, but we see some consistent signal that is suggestive of tidal influence. I'm on the fence as to a recommendation to omit vs retain these sites, which together represent ~2,000 observation-days. On the one hand, the tidal signal is fairly weak and SC values are within the expected range for inland sites (~70-1000 uS/cm). I'm not sure how sensitive the modeling results would be to these signals, especially at daily time steps. Do you have any thoughts on that, @jds485?

**Comment by jds485** [comment]
Thanks! This analysis is helpful to justify the choice of non-tidal model domain. I'm comfortable with keeping the Racoon Creek site. Looking at the discharge and SC record, the tidal influence would be minimal, if it exists at all. I wonder if those signals are wastewater discharges, which would probably also spike at ~2/day for residential areas.

The mainstem site has a larger amplitude signal for SC, about +/- 25 uS/cm (and it also appears in turbidity). I'm leaning towards omitting this site, but I am curious about the signal for the site that looks like it is just upstream of this one.

**Comment by lekoenig** [comment]
> The mainstem site has a larger amplitude signal for SC, about +/- 25 uS/cm (and it also appears in turbidity). I'm leaning towards omitting this site, but I am curious about the signal for the site that looks like it is just upstream of this one.

That makes sense, thanks for looking into those time series a bit further! Regarding the site "just upstream of this one," the map above is deceiving. That site is USGS [01465798](https://waterdata.usgs.gov/pa/nwis/uv/?site_no=01465798), Poquessing Creek, so not along the mainstem river.

_However_, in double-checking that site I found that the way I was initially filtering the SC sites excluded several instantaneous sites (dang!). After fixing that, there are n=50 sites within our 30 km buffer (rather than 42), and 5 mainstem sites (instead of just the one mentioned above, 014670261). The results described above still hold, and I did not see any evidence of tidal signals in the 4 non-mainstem sites that got added with this fix. So I'll focus on the mainstem river sites:

![mainstem_sites](https://user-images.githubusercontent.com/8785034/148254646-a64c6b5a-ccdd-4b97-a57e-bc55f104ff6f.png)

From downstream to upstream:

1) **Site 01477050**

![psd_site_01477050](https://user-images.githubusercontent.com/8785034/148260754-3c867a34-51ed-4b53-aa72-8e4604260d5c.png)

![wavelet_01477050](https://user-images.githubusercontent.com/8785034/148260769-f97174cb-c3eb-45e7-a8a2-4806abb1cd09.png)

2) **Site 01474703**

![psd_site_01474703](https://user-images.githubusercontent.com/8785034/148260821-fbf54b71-d6a3-41c3-bba5-6bb2efea3c23.png)

![wavelet_01474703](https://user-images.githubusercontent.com/8785034/148260833-4f6ce579-199e-4017-9146-8a92c9d12742.png)

3) **Site 01467200**
![psd_site_01467200](https://user-images.githubusercontent.com/8785034/148260869-1aff3741-06ed-4ee8-84ce-a6a64f101d72.png)
![wavelet_01467200](https://user-images.githubusercontent.com/8785034/148260885-192f8a2b-f187-40f0-bffc-76d0cd5367c0.png)

4) **Site 014670261** (this is the site already included above)
![psd_site_014670261](https://user-images.githubusercontent.com/8785034/148260983-c272cd88-b36f-40d8-ae2d-e7626d564710.png)
![wavelet_014670261](https://user-images.githubusercontent.com/8785034/148260987-440a0f2b-8308-4c59-9b1a-f728dac1d6b3.png)

5) **Site 01463500**
![psd_site_01463500](https://user-images.githubusercontent.com/8785034/148261035-847c1837-fb2c-44c1-9b8a-ffe217a45558.png)
![wavelet_01463500](https://user-images.githubusercontent.com/8785034/148261048-e3931ed6-6bd5-490c-baca-dbb1e5bb5962.png)

These plots suggest to me that some tidal influence is apparent for several mainstem sites, and that we may opt to omit the mainstem sites downstream of Trenton, NJ depending on our modeling domain. 

We may be able to keep the most upstream mainstem site in Trenton (site [01463500](https://waterdata.usgs.gov/usa/nwis/uv?01463500)) unless we have additional information about the extent of the salt front. This site reports data at hourly timesteps but I'd still expect to be able to interpret signals at 2-hour frequencies or lower (e.g. 0.5-day tidal periodicities).

**Comment by lekoenig** [comment]
> We can probably use all of these sites for daily average SC prediction, and omit sites downstream of Trenton for sub-daily prediction. If there are discrete samples taken along the main stem downstream of Trenton, we probably should omit them because they would likely not reflect the daily average well. Does this sound like a good plan?

This sounds like a reasonable plan to me. I've added a note to a new project for  sub-daily prediction so that we don't forget about this down the line. 

> I think you said that gaged flows are corrected for sites with tidal influence

I'm not sure what USGS common practice is, but previously I've noticed a derived data product (parameter code 72137) that suggests some tidal filtering of the streamflow data. Here's an example [site](https://waterdata.usgs.gov/nwis/uv?site_no=01193050) in CT. Again, I'm not sure if that's common practice or is unique to local stakeholder needs for that site.
