### ISSUE TITLE
Log summary_multiple_inst_ts.csv updated to current date

### ISSUE THREAD

**Issue by jds485** [USGS-R/drb-inland-salinity-ml#52]
Log file `summary_multiple_inst_ts.csv` will be updated even if the data are the same for the time period of interest. The `end_date` column is the day of build for sites that are active, and the `count_nu` and `count_ts` will also update to the date of the build. For the sites that are active, could we report the end_date as the specified dummy_date and the number of samples up to the dummy date as count_nu?

**Comment by lekoenig** [comment]
I've edited this target in PR #47 so that if a site is active, the returned `end_date` is equal to the `dummy_date`. Regarding the other columns mentioned above, 
- the `count_ts` column is used to tally the number of unique `ts_id`'s that get returned and should not change with build date unless a new `ts_id` gets added for the site. I've left this column as is. 
- I've omitted `count_nu` from this table. We're not necessarily using this log file to tally the observation-days available and so I leave this count to other log files within our pipeline, such as `3_visualize/sitelist_summary.csv`.

I've also opted to move the code that was within the target itself into a separate function - with the changes described above, the target code was > 10 lines within `1_fetch.R`, so probably too long for the phase file. I haven't changed the target name but I'm noting for the future that `p1_nwis_sites_inst_multipleTS_csv` is just too long 😄
